### ISSUE TITLE
Actionable notification response

### ISSUE THREAD

**Issue by PierreScerri** [thehookup/Node-RED-Examples#1]
Hi

Trying to get actionable notification response to work in Node-RED:

configuration.yaml:
```
ios:
  push:
    categories:
      - name: shutter_open_while_away
        identifier: 'shutter_open_while_away'
        actions:
          - identifier: 'CLOSE_SHUTTERS'
            title: "Close Shutters"
            authenticationRequired: no
            destructive: no
```

Node-red sequence:

`[{"id":"8dac9e29.0079b8","type":"server-events","z":"84230fa5.429b","name":"Close Shutters","server":"646a4a07.b2d144","event_type":"","x":620,"y":360,"wires":[["90bfa5cb.5c0a18"]]},{"id":"743f78dc.3cb048","type":"debug","z":"84230fa5.429b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":930,"y":360,"wires":[]},{"id":"90bfa5cb.5c0a18","type":"switch","z":"84230fa5.429b","name":"","property":"payload.event.actionName","propertyType":"msg","rules":[{"t":"eq","v":"CLOSE_SHUTTERS","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":790,"y":360,"wires":[["743f78dc.3cb048"]]},{"id":"646a4a07.b2d144","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open"}]`

When the action button is clicked, the following persistent notification is generated:

Login attempt failed

Login attempt or request with invalid authentication from 192.168.1.254

This is my router.

I'm stumped. What am I doing wrong?
